### ISSUE TITLE
Add Thunder Client to recommended extensions

### ISSUE THREAD

**Issue by floogulinc** [UMM-CSci-3601/3601-iteration-template#1033]
This would actually be very useful from lab 2 on. Thunder Client is a lightweight REST client for VS Code similar to things like Insomnia and Postman.

https://www.thunderclient.com/

https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client

**Comment by NicMcPhee** [comment]
Absolutely. Some students used that last semester and it worked really well, but I forgot to make a note to add that more formally. Thanks!
