### ISSUE TITLE
Replace @angular/flex-layout with css flexbox

### ISSUE THREAD

**Issue by floogulinc** [UMM-CSci-3601/3601-iteration-template#1246]
The [@angular/flex-layout](https://github.com/angular/flex-layout) package is being deprecated and will receive its last update for Angular 15. 

See [this article](https://medium.com/@caerus.karu/farewell-flex-layout-aaa567023769) for more.

**Comment by kklamberty** [comment]
Here are some guides for doing this:

- Somewhat official guide: https://github.com/angular/flex-layout/issues/1426
- Includes a link to the somewhat official guide: https://github.com/angular/flex-layout/issues
- One person's approach [here](https://github.com/angular/flex-layout/issues/1426#issuecomment-1353246488) shows some changes and the accompanying css.
