### ISSUE TITLE
Update documentation on Thunder Client to describe POST requests

### ISSUE THREAD

**Issue by kklamberty** [UMM-CSci-3601/3601-iteration-template#1282]
We have a nice start on documentation for Thunder Client [here](https://github.com/UMM-CSci-3601/3601-iteration-template/blob/main/THUNDER_CLIENT.md), but it would be good to add some further examples including more than GET requests. Having this type of documentation in the Iteration Template repo seems like a good place, and if there are other tools to document at all, other files could be made here. We probably want to refer forward to the documentation here from the other labs (like Lab 2).

**Comment by NicMcPhee** [comment]
I think it's particularly important to have an example of a `POST` or `PUT` request that puts info in the body of the request. You can "fake" all `GET` requests by constructing URLs, but things that need a body can't be done that way, and that's where something like Thunder Client really shines.
