### ISSUE TITLE
Figure out more about the karma test about adding a user in `UserServiceSpec`

### ISSUE THREAD

**Issue by kklamberty** [UMM-CSci-3601/3601-iteration-template#1307]
Yeah, I don't think you shouldn't have gotten `undefined` back here. If you did, then perhaps the mocking wasn't complete? I don't immediately see the problem, though, but it does seem like something's wrong.

_Originally posted by @NicMcPhee in https://github.com/UMM-CSci-3601/3601-iteration-template/pull/1305#discussion_r1118011143_

I posted a comment in the code that was noticed in code review about what happens with the addUser test. I seemed to get back `undefined` rather than something useful. We should look into that. Here is the test:
```typescript
  describe('Adding a user using `addUser()`', () => {
    it('talks to the right endpoint and is called once', waitForAsync(() => {
      // Mock the `httpClient.addUser()` method, so that instead of making an HTTP request,
      // it just returns our test data.
      const USER_ID = 'pat_id';
      const mockedMethod = spyOn(httpClient, 'post').and.returnValue(of(USER_ID));

      // paying attention to what is returned (undefined) didn't work well here,
      // but I'm putting something in here to remind us to look into that
      userService.addUser(testUsers[1]).subscribe((returnedString) => {
        console.log('The thing returned was:' + returnedString);
        expect(mockedMethod)
          .withContext('one call')
          .toHaveBeenCalledTimes(1);
        expect(mockedMethod)
          .withContext('talks to the correct endpoint')
          .toHaveBeenCalledWith(userService.userUrl, testUsers[1]);
      });
    }));
  });
```

**Comment by NicMcPhee** [comment]
I think I figured this out. The problem was that the tests were assuming that it was returning a _string_, when in fact it returns a JSON object with an `:id` field that has the string as its value.

I think that #1369 fixes this. If @kklamberty agrees, she should close this issue.
