### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-iteration-template#264]
There are a bazillion branches on this repo. Many were created by Dependabot and will presumably go away when we finish upgrading everything, but there are also branches left over from merged PRs and the like. We should clean all that stuff up before giving this to students.

**Comment by floogulinc** [comment]
The new template system we use with GitHub Classroom flattens everything down to a single commit on the main branch right?

**Comment by NicMcPhee** [comment]
I think we determined that this isn't true. I don't get that "Include all branches" option when I create an assignment in GitHub Classroom. I don't remember what we actually figured out, though, that explained the different views.

**Comment by floogulinc** [comment]
Yeah we found out that GitHub classroom *always* copies all branches *sigh*. So we will need to make sure this repo is clean before sending out the assignment (or template this repo into a temporary one just for basing the assignment on).

**Comment by NicMcPhee** [comment]
I think we're in good shape now, with almost everything that's left being Dependabot stuff, much of which will go away when we merge in #712.
