### ISSUE TITLE
Say something in the README about `npx webdriver-manager update`

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-iteration-template#273]
If you just try to run the E2E tests, you get an error about webdriver stuff and are told

> Run 'webdriver-manager update' to download binaries'

That doesn't actually work (at least for me), and I've had to do `npx webdriver-manager update` to fix the problem. We don't say anything about that in the README, and probably should?

I think the necessary sequence of events is:

* `npm install` (if you haven't done that already)
* `npx webdriver-manager update`
* `npm install` (again)

Then your E2E tests should run with `npm run e2e`.

❗ Actually, I find that sometimes I have to keep doing and redoing things before I can get this to work. This suggests that I'm either (sometimes) missing something, or there's an important order of events I'm getting wrong. 😢

**Comment by floogulinc** [comment]
This isn't an issue with Cypress so if we complete the switch to that we would be good.

**Comment by NicMcPhee** [comment]
I definitely want to get to Cypress, but I'm growing less and less confident that it will happen this semester unless a whole lot of magic happens. Adding a line or two about the `webdriver` would fix things for now just in case we don't get to Cypress this semester.

**Comment by floogulinc** [comment]
Now that we are using Cypress this isn't an issue anymore.
