### ISSUE TITLE
Have the server return something more useful if you visit `/`

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-iteration-template#312]
At the moment `Server.java` just returns the app name if you visit `/api`:

```java
server.get("/api", ctx -> ctx.result(appName));
```

This doesn't seem super helpful. 

In a perfect world it would be nice to have it return some kind of "usage info" like many CLI tools give you if you call them with no arguments. I think there are ways to do that, but they would complicate things in a variety of ways, and there's already an awful lot going on, so that might not be a great idea.

A simpler approach would be to just have it return a message with a little more information but not try to return full "usage" info.

Another alternative would be to actually provide a custom 404 in the server, and remove this path altogether. The custom 404 message could have the app name and a reminder that you need to visit `/api/…` to help folks in cases where they forget the `/api/` prefix (which happens a lot).

**Comment by floogulinc** [comment]
Usage information would be neat but is difficult because we aren't using anything to actually specify what endpoints there are. Something like OpenAPI can do this and using special annotations on our API endpoints Javalin can actually automatically generate the OpenAPI docs.

**Comment by floogulinc** [comment]
We have added a simple listing of endpoints in #305.
