### ISSUE TITLE
Change the `POST /api/users/new` endpoint to `POST /api/users` 

### ISSUE THREAD

**Issue by helloworld12321** [UMM-CSci-3601/3601-iteration-template#317]
Just a small thing, but it might be a good change to make if we're teaching students how to structure APIs.

Generally, in RESTful APIs, your routes are supposed to represent resources, so they're all named after nouns, not verbs. <sub>(Yes, I know that "new" is an adjective, not a verb. Close enough! 🙃)</sub>

In particular, when you want to create a new object in a collection, it's conventional to send a POST message directly to the collection: https://restfulapi.net/http-methods/#post

**Comment by floogulinc** [comment]
I think this makes sense, do you want to create a PR for it and we'll discuss further in that?

**Comment by helloworld12321** [comment]
Sounds good! I'll try to look at that later today.
