### ISSUE TITLE
Update Mongo

### ISSUE THREAD

**Issue by floogulinc** [UMM-CSci-3601/3601-iteration-template#39]
We should update the version of Mongo we are using globally. This involves changing or removing the version specification in the docker-compose file, removing the version specification in the server and e2e test GH Actions workflow docker services or switching to just starting the now pre-installed mongo server.

**Comment by NicMcPhee** [comment]
It's not clear what the target version is here. I definitely think we should plan on updating from v3.x to v4, but that looks like a fairly complex set of changes so it's not happening right now. Is that what this is proposing?

**Comment by floogulinc** [comment]
You essentially already did this for part of the lab, the GH Actions, in #256

**Comment by floogulinc** [comment]
And it was set in the `docker-compose` file to just be `mongo` in #255

**Comment by floogulinc** [comment]
Actually this is pretty much done though the driver in the server should be updated but I think we are doing that as part of #257
