### ISSUE TITLE
Look at caching node modules and client build artifacts in GH Actions

### ISSUE THREAD

**Issue by floogulinc** [UMM-CSci-3601/3601-iteration-template#42]
See “How to speed up Angular build times with caching” by Mitchell Woodhouse Mckenzie https://link.medium.com/yJG6WGCUA5

Something like that could speed up our GH Actions runs by quite a bit.

**Comment by NicMcPhee** [comment]
@floogulinc Am I right in assuming that this actually happened, quite a while ago? Can we mark this as closed?

**Comment by floogulinc** [comment]
We are caching node modules now and that's probably enough. Theoretically we could also cache the Angular stuff (like what's in `.angular/cache`) to speed up the Angular compilation step.

**Comment by floogulinc** [comment]
Oh wait nevermind we are not caching node modules either, just `.npm` because
> Note: It is not recommended to cache node_modules, as it can break across Node versions and won't work with npm ci

**Comment by NicMcPhee** [comment]
This sounds complex and potentially error prone (as caching often is). It also sounds like a maintenance pain. Should we close this and move on?

**Comment by floogulinc** [comment]
I'm willing to agree this has the potential to break something mysteriously down the line and isn't worth the effort.
