### ISSUE TITLE
Remove bracket pair colorizer from recommended extensions

### ISSUE THREAD

**Issue by floogulinc** [UMM-CSci-3601/3601-iteration-template#594]
The functionality is now built into VS Code and should be enabled in our workspace settings.

![image](https://user-images.githubusercontent.com/1300395/132280818-fcc313ce-ee15-4ac2-8f8c-d1f8aee4a3bd.png)

https://code.visualstudio.com/updates/v1_60#_high-performance-bracket-pair-colorization

**Comment by helloworld12321** [comment]
If we put it in our workspace settings, would there be a way for individual users to turn it off?

(They're a bit too noisy for me, so I usually have the extension disabled 🙂)

**Comment by NicMcPhee** [comment]
I think that if it's in workspace settings, it has to be the same for everyone in the team (but can differ from one team to another). Alternatively we can let them know it's an option that they can turn on/off in their user settings so everyone can make their own choice.

**Comment by floogulinc** [comment]
Yeah workspace setting override user settings. I hadn't thought that some users might not want colored brackets. In that case I would suggest removing the extension suggestion still but recommending users enable that setting for themselves, perhaps in the READMEs or environment setup guides.
