### ISSUE TITLE
Update to Jasmine 4

### ISSUE THREAD

**Issue by helloworld12321** [UMM-CSci-3601/3601-iteration-template#612]
To update Jasmine, we may need to update some karma-related dependencies. See: https://github.com/UMM-CSci-3601/3601-iteration-template/pull/610#issuecomment-1013784234

**Comment by helloworld12321** [comment]
A newly-generated angular project with some simple asynchronous tests work fine.

It's possible that we're doing something specific that triggers this deprecation warning.

**Comment by helloworld12321** [comment]
Ah, there's a fix coming upstream: https://github.com/angular/angular/pull/45025

Thanks to @floogulinc for pointing this out.

**Comment by NicMcPhee** [comment]
So we should update to Zone 0.11.5 and hope that fixes things?

**Comment by helloworld12321** [comment]
@NicMcPhee Looks good to me! I can test it locally, but it seems like Zone 0.11.5 [should fix this bug](https://github.com/angular/angular/blob/main/packages/zone.js/CHANGELOG.md#0115-2022-03-03).

**Comment by helloworld12321** [comment]
Seems to work fine locally! PR opened.

**Comment by kklamberty** [comment]
It looks like we're past all of these now.
