### ISSUE TITLE
Migrate to official Cypress Angular schematic

### ISSUE THREAD

**Issue by floogulinc** [UMM-CSci-3601/3601-iteration-template#678]
There is now an official schematic for Cypress: https://www.npmjs.com/package/@cypress/schematic

We should migrate from `@nrwl/cypress` to `@cypress/schematic`. This will also allow us to remove the `@nrwl/workspace` dependency.

**Comment by NicMcPhee** [comment]
We should do this for Labs 3 and 4 as well.
