### ISSUE TITLE
Do we want to switch to using the body instead of query params in requests?

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-iteration-template#789]
There is an argument to be made that it's better to put the details of a request in the body (which can be encrypted in an HTTPS request) instead of in query params in the path (which can't be encrypted).

Do we want to switch from using query params in our GET requests to instead using the body? Or illustrate both in some fashion?

One thing to be thoughtful about is that if we start using the body for everything it becomes harder for students to try things out and test stuff using "regular" URLs in their browser. We'd probably need to be more explicit/aggressive about introducing a tool like [Postman](https://www.postman.com/) so they'd have a way of trying things out.

If we do go this route it affects everything from [Lab 2](https://github.com/UMM-CSci-3601/3601-lab2_client-server/issues/new) through to the Iteration Template.

**Comment by floogulinc** [comment]
For `GET` requests it is standard to put parameters in the query, I don't think you can even provide a body for `GET` requests. Additionally, the entire URL is encrypted with HTTPS.

**Comment by NicMcPhee** [comment]
Very cool – thanks for clarifying that! I obviously had joined the leagues of confused people on this and thought the URL was exposed. The server name is exposed (it has to be for the initial connection to happen), but the full URL (including the query params) is encrypted after the handshake. I found [this point](https://www.baeldung.com/cs/https-urls-encrypted) useful on the details.

I'll close this since it doesn't need to happen and, as @floogulinc pointed out, really shouldn't since bodies aren't really supposed in `GET` requests.

**Comment by floogulinc** [comment]
Well now with encrypted SNI the server name can be encrypted too but that's far from widely adopted at the moment.
