### ISSUE TITLE
Fix case insensitive queries so they are actually case insensitive

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-iteration-template#793]
Our case insensitive queries in the example `UserController` code aren't actually case insensitive, which came as a non-trivial surprise this semester. Despite what lots of things say on this Internet, adding `"i"` as a `Pattern` property like this:

```java
      filters.add(regex(COMPANY_KEY,  Pattern.quote(ctx.queryParam(COMPANY_KEY)), "i"));
```

doesn't actually work.

@miiiiip did some digging and shared a solution on Slack, which is to add a `?` in front of the `i`:

```java
      filters.add(regex(COMPANY_KEY,  Pattern.quote(ctx.queryParam(COMPANY_KEY)), "?i"));
```

I honestly don't get why we need `"?i"` instead of just `"i"`, but I'm sure it's in some documentation somewhere.

I also tried using the `Pattern.CASE_INSENSITIVE`, but never got that to work. I was pushing pretty fast, though, so it might be worth revisiting that. [This post on "Case-insensitive string matching in Java"](https://www.baeldung.com/java-case-insensitive-string-matching) might be a useful resource.

This also should be applied to [Lab 4](https://github.com/UMM-CSci-3601/3601-lab4-mongo/issues/43).

**Comment by NicMcPhee** [comment]
So I think the problem is that we were basically just adding `i` to the search string, and we needed what they call an "embedded flag expression `(?i)`" to indicate that we were changing "modes" to use case-insensitive searching. Apparently you can do fancy stuff with that to change case-sensitivity locally in subsets of a pattern.

TBH, I think the better solution for us is to use the `CASE_INSENSITIVE` when we compile the `Pattern` rather than futzing about with the rather obscure `(?i)` notation. [The Oracle Java docs cover this in a fairly reasonable way](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/regex/Pattern.html#CASE_INSENSITIVE).

**Comment by kklamberty** [comment]
There are a couple of things I'm just now noticing:
We give examples of filtering on the client (`company` and `name`) and filtering on the server (`age` and `role`). We label those on the client side to help clarify where we are going to do that work. However, we *actually* have something that *looks* like it's going to filter the `company` on the server, and it seems to be the case that the way that flag "i" and the pattern were set up was not working. 

I don't think that this would come up as not working unless someone removed the filtering from the client side. I *suspect* that this shows up more if they attempt to use our server side "filtering" by company as a model for other work like filtering todos, that is where they run into a problem. This might be why I was not able to recreate this bug.

**Comment by NicMcPhee** [comment]
As mentioned in #1290, this appears to have magically fixed itself as it did on [Lab 4](https://github.com/UMM-CSci-3601/3601-lab4-mongo/issues/43).

That said, I do suspect it might be a Good Idea to use the `.compile()` command, although TBH I haven't looked into that.

So I think we should either:

- Just close this and move on, or
- Rename this to be something about improving our use regex `Pattern`, and also move those improvements back to Lab 4.

Thoughts @kklamberty?
