### ISSUE TITLE
Run GH Actions only when relevant files have changed

### ISSUE THREAD

**Issue by floogulinc** [UMM-CSci-3601/3601-iteration-template#83]
For example, we can have the workflow for the server unit tests only run when something in the `server` directory has changed. Same for the client tests and the `client` directory. E2E tests should run for any change still.

**Comment by NicMcPhee** [comment]
I like this idea. Would it be hard? Is there an easy trick in GH Actions to check whether a given sub-tree of the repo has changed?

**Comment by floogulinc** [comment]
If we are requiring certain checks to merge PRs this would be an issue since they wouldn't run. So we can't do this.
