### ISSUE TITLE
Use JavaScript/TypeScript template strings

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-iteration-template#836]
From @jpwalbran on Slack:

> This is a PSA about using typescript template strings, which are things that we haven’t been using and totally should. They allow for having custom formatted strings with values attached that are cleaner than using
> ```
> myString = 'string literal' + value + 'another string literal';
> ```
> Instead, you can use a template string to turn that same expression into
> ```
> myString = `string literal ${value} another string literal`;
> ```
> More information on them can be found [here](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html). 

We totally should be using/modelling this here in the template and in the labs.

**Comment by floogulinc** [comment]
Those docs you link are specifications about using template literals in typescript types. Template literals for regular strings are actually part of regular JavaScript https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
