### ISSUE TITLE
Introduce multi-line strings in the Java code

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-iteration-template#875]
The Java spec files have some really complicated string append stuff that's super hard to read, very error prone, and extremely difficult to debug. I think that a nice way to improve that code would be to use `String.format()` with multi-line strings. Those weren't supported until Java 15, so we'd need to switch to move to a _much_ newer version of Java. If we're going to bother updating, we might as well move to the most recent LTS, which is Java 17.

As example, in `UserControllerSpec.java` there's currently this:

```java
    String testNewUser = "{"
        + "\"name\": \"Test User\","
        + "\"age\": 25,"
        + "\"company\": \"testers\","
        + "\"email\": \"test@example.com\","
        + "\"role\": \"viewer\""
        + "}";
```

The simplest improvement would be to switch to multi-line strings like (which requires at least Java 15):

```java
    String testNewUser = """
      {
        "name": "Test User",
        "age": 25,
        "company": "testers",
        "email": "test@example.com",
        "role": "viewer"
      }
      """
```

If we get that working, then we can extract a function that will use `String.format()` to crank these things out. E.g.,

```java
    String makeTestUser(name, age, company, email, role) {
        return
            String.format(
             """
      {
        "name": "%s",
        "age": %s,
        "company": "%s",
        "email": "%s",
        "role": "%s"
      }
      """,
        name, age, company, email, role)
```

**Comment by kklamberty** [comment]
Neat! For age, I think we'd want a number, but this otherwise looks really neat. Unfortunately, I think we're still in Java 11 land at the moment. I'm not sure if we want to ask about moving up, though, because that does look neat!
