### ISSUE TITLE
Convert Angular 14 untyped form elements to typed forms

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-iteration-template#977]
Angular 14 introduced the idea of strongly typed form elements, which seem to be a substantial improvement that we should embrace. In upgrading to Angular 14, the update scripts identified all "old" form thingies (e.g., `FormGroup`s) and converted them to untyped (e.g., `UntypedFormGroup`).

We should convert all those to the new typed version (i.e., back to `FormGroup`), making sure that in doing so we don't break anything.

The commit 1be195dcb3c4b15646132babba7e53214958c180 explicitly shows every place the update script made changes to untyped form thingies, so we know exactly where we need to make changes.

It looks like the only place we use forms here is in `AddUserComponent`, and concomitantly in `add-user.component.spec.ts`.

This doesn't look like it will be a big deal to address.

**Comment by kklamberty** [comment]
In Lab 4, I pulled changes over from here and mentioned this issue.
commit d95a8f17c49d595d2aa47a0de43f4ebd90d07d69

**Comment by floogulinc** [comment]
I have updated the add user form to use typed forms in #1301
